routes:
  /:
    data: 
      post: page.uneton
    template: post
  /en/:
    data: 
      post: page.sleepless
    template: post
  /en/uneton/:
    template: post
    data:
      post: page.sleepless
  /en/docs/:
    template: post
    data:
      post: page.docs_en

collections:
  /news/:
    permalink: /{slug}/
    template: index

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
