routes:
  /:
    data: 
      post: page.index-fi
    template: post
  /en/:
    data: 
      post: page.index-en
    template: post

collections:
  /news/:
    permalink: /news/{slug}/
    template: news

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
