routes:
  /:
    data: 
      post: page.index-fi
    template: post
  /en/:
    data: 
      post: page.index-en
    template: post

collections:
  /en/:
    permalink: /en/{slug}/
    filter: 'tag:en'
  /fi/:
    permalink: /fi/{slug}/
    filter: 'tag:fi'

taxonomies:
  tag: /tag/{slug}/
  author: /author/{slug}/
